config/routes.rb
Rails.application.routes.draw do
  get 'bittrexprices/index'

  get 'bittrexprices/new'

  get 'bittrexprices/create'

  get 'bittrexprices/save'

  get 'bittrexprices/delete'

  get 'bittrexprices/destroy'

  get 'bittrex_prices/new'

  get 'bittrex_prices/create'

  get 'bittrex_prices/save'

  get 'bittrex_prices/delete'

  get 'bittrex_prices/destroy'

    root 'main#index'
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
    match '/signin',  to: 'sessions#new',         via: 'get'
    match '/signout', to: 'sessions#destroy',     via: 'delete'
    post 'main/get_data', to: 'main#get_data'

end

app/models/binanceprice.rb
class Binanceprice < ActiveRecord::Base
	serialize :eth, JSON
	serialize :btc, JSON
	serialize :bch, JSON
	serialize :ltc, JSON
	serialize :dash, JSON
	serialize :etc, JSON
	serialize :zec, JSON
end

app/models/bitfinexprice.rb
class Bitfinexprice < ActiveRecord::Base
	serialize :eth, JSON
	serialize :btc, JSON
	serialize :bch, JSON
	serialize :ltc, JSON
	serialize :dash, JSON
	serialize :etc, JSON
	serialize :zec, JSON
end

app/models/bittrexprice.rb
class Bittrexprice < ActiveRecord::Base

	serialize :eth, JSON
	serialize :btc, JSON
	serialize :bch, JSON
	serialize :ltc, JSON
	serialize :dash, JSON
	serialize :etc, JSON
	serialize :zec, JSON
	
end

app/models/domain.rb
class Domain < ActiveRecord::Base
	has_many :users
end

app/models/exmoprice.rb
class Exmoprice < ActiveRecord::Base

	serialize :eth, JSON
	serialize :btc, JSON
	serialize :bch, JSON
	serialize :ltc, JSON
	serialize :dash, JSON
	serialize :etc, JSON
	serialize :zec, JSON
	
end

app/models/gateprice.rb
class Gateprice < ActiveRecord::Base
	serialize :eth, JSON
	serialize :btc, JSON
	serialize :bch, JSON
	serialize :ltc, JSON
	serialize :dash, JSON
	serialize :etc, JSON
	serialize :zec, JSON
end

app/models/hitbtcprice.rb
class Hitbtcprice < ActiveRecord::Base

	serialize :eth, JSON
	serialize :btc, JSON
	serialize :bch, JSON
	serialize :ltc, JSON
	serialize :dash, JSON
	serialize :etc, JSON
	serialize :zec, JSON
	
end

app/models/krakenprice.rb
class Krakenprice < ActiveRecord::Base
	serialize :eth, JSON
	serialize :btc, JSON
	serialize :bch, JSON
	serialize :ltc, JSON
	serialize :dash, JSON
	serialize :etc, JSON
	serialize :zec, JSON
end

app/models/okexprice.rb
class Okexprice < ActiveRecord::Base

	serialize :eth, JSON
	serialize :btc, JSON
	serialize :bch, JSON
	serialize :ltc, JSON
	serialize :dash, JSON
	serialize :etc, JSON
	serialize :zec, JSON
	
end

app/models/poloprice.rb
class Poloprice < ActiveRecord::Base

	serialize :eth, JSON
	serialize :btc, JSON
	serialize :bch, JSON
	serialize :ltc, JSON
	serialize :dash, JSON
	serialize :etc, JSON
	serialize :zec, JSON
	
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :domain

	before_save { email.downcase! }
	before_create :create_remember_token
 	validates :name, presence: true, length: { maximum: 50 }
 	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
 	has_secure_password
 	validates :password, length: { minimum: 6 }





 	def User.new_remember_token
    	SecureRandom.urlsafe_base64
  	end

  	def User.digest(token)
    	Digest::SHA1.hexdigest(token.to_s)
  	end

  	private

    	def create_remember_token
      		self.remember_token = User.digest(User.new_remember_token)
    	end
end

app/models/zbprice.rb
class Zbprice < ActiveRecord::Base
	serialize :eth, JSON
	serialize :btc, JSON
	serialize :bch, JSON
	serialize :ltc, JSON
	serialize :dash, JSON
	serialize :etc, JSON
	serialize :zec, JSON
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	def index

	end


	def get_data

		amount = params[:amount].to_i
		@data = []
		if amount == 0
			@data << {error: 'Invalid value!'}
		else
			
			coin_list = ["ETH", "BTC", "BCH", "LTC", "DASH", "ETC", "ZEC"]
			
			@data << coin_list

			@data << Hitbtc::get_all_prices(amount)
			@data << Polo::get_all_prices(amount)
			@data << Exmo::get_all_prices(amount)
			@data << Okex::get_all_prices(amount)
			@data << Bittrex::get_all_prices(amount)
			@data << Kraken::get_all_prices(amount)
			@data << Bitfinex::get_all_prices(amount)
			@data << Binance::get_all_prices(amount)
			@data << Zb::get_all_prices(amount)
			@data << Gate::get_all_prices(amount)

		end
		render :json => @data
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
 	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
    	if user && user.authenticate(params[:session][:password]) && (user.domain.company_id == params[:session][:domain_id])
      		sign_in user
          flash[:notice] = 'Successful login'
      		redirect_back_or user
    	else
      		flash[:alert] = 'Invalid email/password combination'
      		redirect_to signin_path
    	end
	end

	def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :signed_in_user, only: [:show]		
	before_action :correct_user,   only: [:show]


	def show
		@user = User.find(params[:id])
	end

	
		
	
	

	private

    	def user_params
    		params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :domain_id)
    	end

    	def signed_in_user
      		unless signed_in?
        		store_location
        		redirect_to signin_url, alert: "Please sign in."
      		end
    	end

    	def correct_user
      		@user = User.find(params[:id])
      		redirect_to(root_url) unless current_user?(@user)
    	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def custom_bootstrap_flash
  		flash_messages = []
  		flash.each do |type, message|
    		type = 'success' if type == 'notice'
    		type = 'error'   if type == 'alert'
    		text = "<script>toastr.#{type}('#{message}');</script>"
    		flash_messages << text.html_safe if message
  		end
  		flash_messages.join("\n").html_safe
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def sign_in(user)
    	remember_token = User.new_remember_token
    	cookies.permanent[:remember_token] = remember_token
    	user.update_attribute(:remember_token, User.digest(remember_token))
    	self.current_user = user
  	end

  	def signed_in?
    	!current_user.nil?
  	end

  	def current_user=(user)
    	@current_user = user
  	end

  	def current_user
    	remember_token = User.digest(cookies[:remember_token])
    	@current_user ||= User.find_by(remember_token: remember_token)
  	end

    def current_user?(user)
      user == current_user
    end


    def sign_out
      current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
      cookies.delete(:remember_token)
      self.current_user = nil
    end


    def redirect_back_or(default)
      redirect_to(session[:return_to] || default)
      session.delete(:return_to)
    end

    def store_location
      session[:return_to] = request.url if request.get?
    end

    
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Zeus
  </small>
  <nav>
    <ul>
      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
          <%= link_to "Project Zeus", root_path, id: "logo", class: 'navbar-brand' %>
        </div>
        <div id="navbar" class="navbar-collapse collapse pull-right">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "Home", root_path %></li>
            

            
            <% if signed_in? %>
              <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
            <% else %>
              <li><%= link_to "Log in", signin_path %></li>
            <% end %>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project Zeus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
</head>
<body>

	<%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>








</body>
</html>

app/views/main/index.html.erb
      <!-- Main jumbotron for a primary marketing message or call to action -->
      <!--div class="jumbotron" style="margin-top:100px;">
        
        <div class='row'>
        <div class='col-sm-6 col-sm-offset-3'>
          < form_for(:session, url: sessions_path) do |f| %>

          < f.label :domain_id >
          < f.text_field :domain_id >

          < f.label :email %>
          < f.text_field :email, class: 'form-control' %>

          < f.label :password %>
          < f.password_field :password, class: 'form-control' %>

          < f.submit "Sign in", class: "btn btn-large btn-primary" %>
        < end %>
        </div>
        </div>
      </div-->

  


<div class="jumbotron" style="margin-top:100px;border-radius:0px">
<div class="row">
  <div class="col-xs-12" style="margin-left:0px;padding-left:0px;">
    <code>N/A: Not enough source to buy/sell.</code>
  </div>
  <div class="col-xs-12" style="margin-left:0px;padding-left:0px;">
    <code>-: Coin is not tradeable for that exchange.</code>
  </div>
</div>
  <div class='row' style="margin-top:30px;">
  <div><span>Initial Capital:</span> <span id="capital">-</span></div>
  <div class="col-xs-3" style="margin-left:0px;padding-left:0px;margin-top:10px;">
  <span>e.g. 10000</span>
    <input type="text" name="amount" class="form-control" id="amount" style="border-radius:0px"></input>
  </div>
  
    <div class="col-xs-12" style="margin-left:0px;padding-left:0px;">
      <button class="btn btn-large btn-primary" id="refresh" style="margin-top:10px;border-radius:0px;background-color: #27408B;">Refresh</button>
    </div>
  
  </div>
</div>





   <div class="container">
        
        <div id="toolbar">
            
        </div>
        <table id="table-ask"
               data-toggle="table"
               data-toolbar="#toolbar"
               data-height="360"
               data-url="">
            <thead>
            <tr>
                <th data-field="id">Ask</th>
                <th data-field="HitBtc">Hitbtc</th>
                <th data-field="Polo">Polo</th>
                <th data-field="Exmo">Exmo</th>
                <th data-field="Okex">Okex</th>
                <th data-field="Bittrex">Bittrex</th>
                <th data-field="Kraken">Kraken</th>
                <th data-field="Bitfinex">Bitfinex</th>
                <th data-field="Binance">Binance</th>
                <th data-field="Zb">Zb</th>
                <th data-field="Gate">Gate</th>
            </tr>
            </thead>
        </table>
    </div>

       <div class="container" style="margin-top:50px;">
        
        <div id="toolbar-bid">
        </div>
        <table id="table-bid"
               data-toggle="table"
               data-toolbar-bid="#toolbar-bid"
               data-height="360"
               data-url="">
            <thead>
            <tr>
                <th data-field="id">Bid</th>
                <th data-field="HitBtc">Hitbtc</th>
                <th data-field="Polo">Polo</th>
                <th data-field="Exmo">Exmo</th>
                <th data-field="Okex">Okex</th>
                <th data-field="Bittrex">Bittrex</th>
                <th data-field="Kraken">Kraken</th>
                <th data-field="Bitfinex">Bitfinex</th>
                <th data-field="Binance">Binance</th>
                <th data-field="Zb">Zb</th>
                <th data-field="Gate">Gate</th>
            </tr>
            </thead>
        </table>
    </div>

<script>
    var $tableAsk = $('#table-ask'),
        $tableBid = $('#table-bid'),
        $button = $('#refresh');
    $(function () {
        $button.click(function () {
          callexchanges();
        });
    });
    function callexchanges() {
      $.LoadingOverlay("show");
            var asks = [],
                bids = [];
      
        $.ajax({
        url: 'main/get_data', 
        type: 'POST',
        data: {amount: $('#amount').val()},
        success: function(data) { 
          console.log(data);
          $('#capital').html('-');
          if (data[0].error) {
            $('#capital').html('<span style="color:rgb(235, 43, 54);">'+data[0].error+'</span>' );
          }else {
            $('#capital').html('$'+$('#amount').val());
            for (var k = 0, len=data[0].length; k < len; k++) {
                var exc_hash = {
                    id: data[0][k]
                  };
                var exc_hash2 = {
                    id: data[0][k]
                  };
                for (var m = 1, len2=data.length; m < len2; m++) {
                  if ((data[m][k]) == null) {
                      '-'
                  }else {
                    exc_hash[(data[m][k][7])] = ((data[m][k][1][2] == 'OK') ? data[m][k][1][0] : data[m][k][1][2]);  
                    exc_hash2[(data[m][k][7])] = ((data[m][k][3][2] == 'OK') ? data[m][k][3][0] : data[m][k][3][2]);  
                  }

                  
                  
                }
                asks.push(exc_hash);
                bids.push(exc_hash2);
              }
              
              successfunc(asks, bids);
          }

        },
        complete: function() {
          $.LoadingOverlay("hide");
        }
        
      });
        
        


    }
  function successfunc(asks, bids) {
    $tableAsk.bootstrapTable('removeAll');
    $tableBid.bootstrapTable('removeAll');
    $tableAsk.bootstrapTable('append', asks);
    $tableBid.bootstrapTable('append', bids);

  }
</script>

app/views/users/show.html.erb
<div class="center hero-unit">	

  <h1><%= @user.domain.company_name %></h1>		
  <h6>
  		<%= @user.domain.address %> | <%= @user.domain.city %> | <%= @user.domain.country %> | <%= @user.domain.zip_code %>
  	</h6>
  <h2>
    <%= @user.domain.company_id %>
  </h2>

  <div>
  	
  	<h5>
  		<div><%= @user.name %></div>
  		<div><%= @user.email %></div>
  	</h5>
  </div>

  
  
</div>